function displayFG;
persistent f faces FNum INum
if ~isempty(get(gcbo,'Type'))     % if not called from menu, update values
    h=gcbo;
    ctl=get(h,'Tag');       % who initiated it!
    switch ctl
        case 'ImgNumSld'                    % slider
            hs  = findobj('Tag','ImgNumEdt');   % update text
            INum =  round(get(h,'value'));
            set(hs,'string',num2str(INum));
        case 'ImgNumEdt'                    % text
            INum =  round(str2num(get(h,'string'))); % is a string
            hs = findobj('Tag','ImgNumSld');
            set(hs,'value',INum);
            
        case 'FeatureNumSld'                    % slider
            hs  = findobj('Tag','FeatureNumEdt');   % update text
            FNum =  round(get(h,'value'));
            set(hs,'string',num2str(FNum));
        case 'FeatureNumEdt'                    % text
            FNum =  round(str2num(get(h,'string'))); % is a string
            hs = findobj('Tag','FeatureNumSld');
            set(hs,'value',FNum);
    end
        
    set(gca,'Position',[30 80 96 96],'Units','pixels');
    DisplayFeature(24,24,f(:,FNum));
    feat=get(get(gca,'Children'),'CData');  % get back feature
    featu=uint8(feat*255);  %convert 
    
    img=reshape(faces(INum,:),24,24);   % overlay image
    imgc = zeros([size(img) 3]);    % rgb!
    imgc(:,:,1)=uint8(255*(img-min(img(:)))/(max(img(:))-min(img(:))));
    imgc(:,:,2)=imgc(:,:,1);    %same intensity
    imgc(:,:,3)=imgc(:,:,1);
    
    imgtmp = imgc(:,:,3); imgtmp=imgtmp(:);
    imgtmp(find(featu(:)==255))=100;
    imgc(:,:,3) = reshape(imgtmp,24,24);
    
    imgtmp = imgc(:,:,2); imgtmp=imgtmp(:);
    imgtmp(find(featu(:)==0))=100;
    imgc(:,:,2) = reshape(imgtmp,24,24);
    
    imshow(uint8(imgc));
    %    imshow(bitor(ftu,imgu));
    padFace = faces(INum,:);
    padFace= padJN(padFace);        % zero pad

    cumImg = cumImageJN(padFace)*f(:,FNum);
    h=findobj('Tag','FeatTxt');
    set(h,'String',num2str(cumImg));
else
    % initialize controls
%    if ((exist('f') == 0) | isempty(f))      % are features loaded?

    load images.mat;load features.mat;
        %    end
    numFeatures = size(f,2);
    numImgs = size(faces,1);    % stored in row order!
    %    numImages = size    
    x(1)= 10;y=5;x_edt = 140;
    x(2)= 130;
    ctl_hgt = 20;
    
    % create fig
    h0 = figure('Color',[0.7 0.7 0.7], ...
        'MenuBar','none','ToolBar','none', ...
        'NumberTitle','off', ...
        'Name','Select feature to show',...
        'Position',[150 300 200 200], ...
        'Tag','Fig1', ...
        'UserData','[]');
    
    h = uicontrol('Parent',h0, ...
        'Position',[x(1) y+15 200 ctl_hgt], ...
        'String','Feature #', ...
        'Style','text', ...
        'Tag','ftext');
    
    h = uicontrol('Parent',h0,...
        'Callback','displayFG;',...
        'Max',numFeatures, ...
        'Min',1, ...
        'SliderStep',[1/(numFeatures - 1) 10/(numFeatures - 1)], ...
        'Position',[x(1) y 110 ctl_hgt], ...
        'Style','slider', ...
        'Tag','FeatureNumSld', ...
        'Value',1);
        FNum = 1;   % init    
    h = uicontrol('Parent',h0,...
        'Callback','displayFG;',...
        'Position',[x(2) y 50 ctl_hgt],...
        'String',num2str(1),...
        'Style','edit', ...
        'Tag','FeatureNumEdt');
% image info    
    h = uicontrol('Parent',h0,...
        'Callback','displayFG;',...
        'Max',numImgs, ...
        'Min',1, ...
        'SliderStep',[1/(numImgs - 1) 10/(numImgs - 1)], ...
        'Position',[x(1) y+25 110 ctl_hgt], ...
        'Style','slider', ...
        'Tag','ImgNumSld', ...
        'Value',1);
        INum = 1;   % init    
    
    h = uicontrol('Parent',h0,...
        'Callback','displayFG;',...
        'Position',[x(2) y+25 50 ctl_hgt],...
        'String',num2str(1),...
        'Style','edit', ...
        'Tag','ImgNumEdt');

    h = uicontrol('Parent',h0,...
        'Callback','displayFG;',...
        'Position',[x(2) y+55 50 ctl_hgt],...
        'String',num2str(0),...
        'Style','text', ...
        'Tag','FeatTxt');
    
    % OK button, return with uiresume!
    h = uicontrol('Parent',h0, ...
        'Callback','close(gcbf);uiresume;',...
        'Position',[x(2)+55 y 40 ctl_hgt], ...
        'String','Close', ...
        'Tag','pbtn');
    
    %h= axes('Parent',h0,'Tag','ImgFeature','Units','pixels','Visible','off');
    %h= axes('Parent',h0,'Tag','ImgFeature','Position',[30 50 180 180],'Units','pixels');
    h= axes('Parent',h0,'Tag','ImgFeature','Position',[30 80 96 96],'Units','pixels');
end